config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  devise_for :users
  get 'home/index'
  get 'posts/index'
  get 'recommand/index'
  get 'home/recommand'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts

  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  before_save :translate

  private

  def translate
    case job
    when 'fman'
      self.job = '낚시꾼'
    when 'sman'
      self.job = '창지기'
    when 'lman'
      self.job = '등대지기'
    when 'wman'
      self.job = '파도잡이'
    when 'gman'
      self.job = '길잡이'
    end
    case sex
    when 'Male'
      self.sex = '남자'
    when 'Female'
      self.sex = '여자'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [:name, :sex, :address, :tele_phone, :habbit, :strong_point, :job, :introduce_myself]
    )
    devise_parameter_sanitizer.permit(
      :account_update,
      keys: [:name, :sex, :address, :tele_phone, :habbit, :strong_point, :job, :introduce_myself]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/recommand_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.order(:created_at)
  end

  def show

    @user = User
    .find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<html>
  <head>
    <head>
      <script type="text/javascripts">
        function toggle_visibilitiy(id){ var e = document.getElementById(id); if(e.style.display == 'block') e.style.display = 'none'; else { e.style.display = 'block' } }
      </script>
    </head>
  </head>
  <body>

    <!--Digitool main page-->
    <div id="head-main">
      <div class="parallax"></div>
      <div class="content">
        <h1>
          <span class="card-title">Welcome to Digitool</span>
        </h1>
        <p>Start yout project</p>
        <div class="empty-spacing"></div>
        <div class="empty-spacing"></div>

        <%= link_to users_path, class:"semi-transparent-button hoverable" do %>
        <strong>Join in</strong>
        <% end %>
      </div>
      <!--Digitool Introduction -->
      <div class="empty-spacing"></div>
    </div>
    <div class="empty-spacing"></div>
    <div class="so-widget-sow-headline so-widget-sow-headline-default-0f5a0189729b">
      <div class="sow-headline-container ">
        <h1 class="sow-headline">
          <span class="card-title">
            <u>ABOUT Digitool</u>
          </span>
        </h1>
      </div>
    </div>
    <div class="empty-spacing"></div>

    <div style="height:auto;background-color:white:font-size:36px">
      Scroll Up and Down this page to see the parallax scrolling effect. This div is just here to enable scrolling. Tip: Try to remove the background-attachment property to remove the scrolling effect.
    </div>
    <div class="empty-spacing"></div>
    <div class="empty-spacing"></div>

    <!---트립메이트의 3가지특성-------->
    <div class="container">
      <div class="row">
        <div id="charoftm" class="col s12 centralize center">
          <div class="col s12 m4 box-solution">
            <div class="icon-block">
              <i class="large material-icons">flash_on</i>
              <h3 class="center blue-text text-lighten-2 light">
                Find your Role</h3>
              <p class="grey-text text-darken-3 col s12 centralize">자신의 역할을 결정하세요. 여행시 어떤역을해야될지 고민되셧죠? TripMate는 여행시 필요한 역할분담을 할수있도록 도와줍니다.</p>
            </div>
          </div>

          <div class="col s12 m4 box-solution">
            <div class="icon-block">
              <i class="large material-icons">supervisor_account</i>
              <h3 class="center blue-text text-lighten-2 light">
                Find your Mates</h3>
              <p class="grey-text text-darken-3 col s12 centralize">
                자신과 코드가 맞는 여행친구를 찾아보세요. 가끔은 색다른친구들과 여행을떠나는것도 좋은경험이에요.</p>
            </div>
          </div>

          <div class="col s12 m4 box-solution">
            <div class="icon-block">
              <i class="large material-icons">thumb_up</i>
              <h3 class="center blue-text text-lighten-2 light">Find your MVP</h3>
              <p class="grey-text text-darken-3 col s12 centralize">
                이번여행의 MVP가 되어보세요. 모든사람들이 여행시 당신을 찾게될겁니다.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="empty-spacing"></div>
    <div class="empty-spacing"></div>

    <!--역할분담-->
    <div class="duty-container">
      <h1 class="sow-headline">
        <span class="card-title">
          <u>T.O.P의 역할분담</u>
        </span>
      </h1>
      <div class="empty-spacing"></div>
      <div class="container">
        <div class="row">
          <div class="col s4">
            <div class="icon-block">
              <%= image_tag('giljob.jpg', class:'image1')%>
              <h3 class="center blue-text text-lighten-2 light">
                길잡이</h3>
              <p class="grey-text text-darken-3 col s12 centralize">
                길잡이는 여행에서 운전을 담당하고있는 포지션인데요, 운전면허가 필수조건인 포지션입니다.</p>
            </div>
          </div>

          <div class="col s4">
          <li class="collection-header">
            <h5>Recent Project</h5>
          </li>
          <div class="collection">
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
            <a href="#!" class="collection-item">Alvin</a>
          </div>
        </div>

        <div class="col s4">
          <div class="icon-block">
            <%= image_tag('gdungda.jpg', class:'image1')%>
            <h3 class="center blue-text text-lighten-2 light">등대지기</h3>
            <p class="grey-text text-darken-3 col s12 centralize">
              등대지기는 언제,어디서든 여행을 게획하며 여러 포지션과 좋은 시너지를 발휘할 수 있는 필수적인 포지션입니다.</p>
          </div>
        </div>
      </div>

      <div class="empty-spacing"></div>

      <div class="empty-spacing"></div>

      <!--Digitool increase efffect-->
      <div id="tm">
        <br></br>
        <div class="so-widget-sow-headline so-widget-sow-headline-default-0f5a0189729b">
          <div class="sow-headline-container">
            <div class="empty-spacing"></div>
            <h2 class="sow-headline">
              <span class="card-title">

                <h2>
                  <u>In the Digitool</u>
                </h2>

              </span>
            </div>
          </div>
          <div class="empty-spacing"></div>
          <div class="empty-spacing"></div>
          <div class="empty-spacing"></div>

          <div class="tmsection">
            <div class="row">
              <div id="charoftm" class="col s12 centralize center">
                <div class="col s12 m4 box-solution">
                  <i class="medium material-icons">drive_eta</i>
                  <div class="icon-block">
                    <p class="grey-text text-darken-3 col s12 centralize">
                      지금까지 여행한
                      <span style="color: #FF0000;font-weight:bold;">Project</span>
                      <div class="counter col s12" data-count="150">0</div>
                    </p>
                  </div>
                </div>
                <div class="col s12 m4 box-solution">
                  <i class="medium material-icons">directions_run</i>
                  <div class="icon-block">
                    <p class="grey-text text-darken-3 col s12 centralize">
                      지금까지 여행한
                      <span style="color: #FF0000;font-weight:bold;">d</span>
                      <div class="counter col s12" data-count="85">0</div>
                    </p>
                  </div>
                </div>
                <div class="col s12 m4 box-solution">
                  <i class="medium material-icons">location_city</i>
                  <div class="icon-block">
                    <p class="grey-text text-darken-3 col s12 centralize">
                      지금까지의
                      <span style="color: #FF0000;font-weight:bold;">joined</span>
                      <div class="counter col s12" data-count="200">0</div>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="empty-spacing"></div>
        </div>

      </body>

app/views/home/recommand.html.erb
<div class="empty-spacing"></div>
<div class="empty-spacing"></div>
<ul id="tabs-swipe-demo" class="tabs">
   <li class="tab col s3"><a href="#test-swipe-1"><span class="card-title">
           N분의 여행</span>
   </h2></a></li>
   <li class="tab col s3"><a class="active" href="#test-swipe-2"><span class="card-title">
           부르는게 맛집</span>
   </h2></a></li>
   <li class="tab col s3"><a href="#test-swipe-3"><span class="card-title">
           let's 축제</span>
   </h2></a></li>
 </ul>

 <div id="test-swipe-1" class="col s12"><div class="empty-spacing"></div>
 <div class="empty-spacing"></div>
   <div class="container">
     <div class="row">
       <div class="col s7">
         <section class="hoverEffect">
           <%= image_tag('seoultrip.jpg', class:'image')%>
           <div class="txt">
             <h3>서울</h3>청계천</div>
         </section>
       </div>
       <div class="col s5">
         <section class="hoverEffect">
           <%= image_tag('Junjutrip.png', class:'image')%>
           <div class="txt">
             <h3>전주</h3>한옥마을
           </div>
       </section>
       </div>
     </div>
     <div class="row">
       <div class="col s4">
         <section class="hoverEffect">
           <%= image_tag('youngintrip.jpg', class:'image')%>
           <div class="txt">
             <h3>용인</h3>에버렌드</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
            <%= image_tag('damyangtrip.jpg', class:'image')%>
           <div class="txt">
             <h3>담양</h3>대나무숲</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
             <%= image_tag('gyungjutrip.jpg', class:'image')%>
           <div class="txt">
             <h3>경주</h3>불국사</div>
         </section>
      </div>
     </div>
     <div class="row">
       <div class="col s6">
         <section class="hoverEffect">
           <%= image_tag('busantrip.png', class:'image')%>
           <div class="txt">
             <h3>부산</h3>해운대</div>
         </section>
       </div>
       <div class="col s6">
       <section class="hoverEffect">
           <%= image_tag('jejutrip.jpg', class:'image')%>
           <div class="txt">
             <h3>제주</h3>성산일출봉</div>
         </section>
       </div>
     </div>
   </div>
   <div class="empty-spacing"></div>
</div>


 <div id="test-swipe-2" class="col s12"><div class="empty-spacing"></div>
 <div class="empty-spacing"></div>
   <div class="container">
     <div class="row">
       <div class="col s5">
         <section class="hoverEffect">
           <%= image_tag('seoulfood.jpg', class:'image')%>
           <div class="txt">
             <h3>서울</h3>곱창</div>
         </section>
       </div>
       <div class="col s7">
         <section class="hoverEffect">
           <%= image_tag('yonginfood.jpg', class:'image')%>
           <div class="txt">
             <h3>용인</h3>도토리부추전
           </div>
       </section>
       </div>
     </div>
     <div class="row">
       <div class="col s4">
         <section class="hoverEffect">
              <%= image_tag('gyoungjufood.jpg', class:'image')%>
           <div class="txt">
             <h3>경주</h3>경주빵</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
            <%= image_tag('damyangfood.jpg', class:'image')%>
           <div class="txt">
             <h3>담양</h3>떡갈비</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
           <%= image_tag('junjufood.jpg', class:'image')%>
           <div class="txt">
             <h3>전주</h3>비빔밥</div>
         </section>
      </div>
     </div>
     <div class="row">
       <div class="col s7">
         <section class="hoverEffect">
           <%= image_tag('jejufood.png', class:'image')%>
           <div class="txt">
             <h3>제주</h3>흑돼지</div>
         </section>
       </div>
       <div class="col s5">
       <section class="hoverEffect">
         <%= image_tag('busanfood.jpg', class:'image')%>
           <div class="txt">
             <h3>부산</h3>막회</div>
         </section>
       </div>
     </div>
   </div>
   <div class="empty-spacing"></div>
</div>


 <div id="test-swipe-3" class="col s12"><div class="empty-spacing"></div>
 <div class="empty-spacing"></div>
   <div class="container">
     <div class="row">
       <div class="col s7">
         <section class="hoverEffect">
           <%= image_tag('seoulfest.png', class:'image')%>
           <div class="txt">
             <h3>서울</h3>벚꽃축제</div>
         </section>
       </div>
       <div class="col s5">
         <section class="hoverEffect">
           <%= image_tag('incheonfest.jpg', class:'image')%>
           <div class="txt">
             <h3>인천</h3>락페스티벌
           </div>
       </section>
       </div>
     </div>
     <div class="row">
       <div class="col s4">
         <section class="hoverEffect">
           <%= image_tag('yonginfest.jpg', class:'image')%>
           <div class="txt">
             <h3>용인</h3>거리축제</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
           <%= image_tag('damyangfest.jpg', class:'image')%>
           <div class="txt">
             <h3>담양</h3>대나무축제</div>
         </section>
       </div>
       <div class="col s4">
         <section class="hoverEffect">
           <%= image_tag('yangpyungfest.jpg', class:'image')%>
           <div class="txt">
             <h3>양평</h3>빙어축제</div>
         </section>
      </div>
     </div>
     <div class="row">
       <div class="col s6">
         <section class="hoverEffect">
           <%= image_tag('busanfest.jpg', class:'image')%>
           <div class="txt">
             <h3>부산</h3>모래축제</div>
         </section>
       </div>
       <div class="col s6">
       <section class="hoverEffect">
         <%= image_tag('jejufest.JPG', class:'image')%>
           <div class="txt">
             <h3>제주</h3>감귤축제</div>
         </section>
       </div>
     </div>
   </div>
   <div class="empty-spacing"></div>
</div>
<!--<h2 class="tripmate-intro">
<span class="card-title">
        N분의 여행</span>
</h2>
</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Digitool</title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <style>
    @import url(http://fonts.googleapis.com/earlyaccess/hanna.css);
    @import url( 'https://fonts.googleapis.com/css?family=Pacifico');
    @import url( 'https://fonts.googleapis.com/css?family=Sedgwick+Ave');

    </style>
  </head>

  <body>
    <%= render "shared/heading" %>
    <%= render "shared/devise" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col offset-s2"></div>
    <h4 class="col s8">여행지 찾기</h4>
    <div class="col offset-s2"></div>
    <div class="divider"></div>
    <br>
  </div>
  <div class="row">
    <div class="col offset-s2"></div>
    <div class="input-field col s8">
      <select>
        <option value="" disabled selected>Choose your option</option>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
      </select>
      <label>가고 싶은 여행지를 선택하세요</label>
    </div>
    <div class="col offset-s2"></div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col offset-s2"></div>
    <div class="col s8">
      <div class="trip-box">
        <div class="card">
          <div class="card-image">
            <%= image_tag('3.png')%>
            <span class="card-title">Card Title</span>
            <%=link_to new_post_path, class:"btn-floating halfway-fab waves-effect waves-light red" do%>
              <i class="material-icons">add</i>
            <% end %>
          </div>
          <div class="card-content">
            <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col offset-s2"></div>
  </div>
  <div class="row">
    <div class="col offset-s2"></div>
    <div class="col s8">
      <div class="trip-box">
        <div class="card">
          <div class="card-image">
            <%= image_tag('3.png')%>
            <span class="card-title">Card Title</span>
            <%=link_to new_post_path, class:"btn-floating halfway-fab waves-effect waves-light red" do%>
              <i class="material-icons">add</i>
            <% end %>
          </div>
          <div class="card-content">
            <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col offset-s2"></div>
  </div>
</div>

app/views/posts/new.html.erb
POST NEW!!

app/views/shared/_devise.html.erb
<% if notice %>
  <script type="text/javascript">
    Materialize.toast('<%= notice %>', 4000, 'green')
  </script>
<% end %>
<% if alert %>
  <script type="text/javascript">
    Materialize.toast('<%= alert %>', 4000, 'red')
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s12 m2 box-solution">
          Digitool
        </div>
        <div class="col s12 m2 box-solution">
          Privacy
        </div>
        <div class="col s12 m2 box-solution">
          Terms
        </div>
        <div class="col s12 m2 box-solution">
          Contact
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_heading.html.erb
<!--logo and nevigation--->
  <nav>
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">
        <span class="card-title"><i class="material-icons">card_travel</i>Digitool</span></a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="valign-wrapper right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
          <span class="pr40"><%= current_user.name%></span>
        </li>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="여행 찾기">
          <%= link_to posts_path do %>
            <span><i class="material-icons">find_replace</i></span>
          <% end %>
        </li>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="여행추천">
          <%= link_to home_recommand_path do %>
            <span><i class="material-icons">directions_car</i></span>
          <% end %>
        </li>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="마이 페이지">
          <%= link_to user_path(current_user) do %>
            <i class="material-icons">face</i>
          <% end %>
        </li>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="로그아웃">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="material-icons">power_settings_new</i>
          <% end %>
        </li>
      <% else %>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="회원가입">
          <%= link_to new_user_registration_path do %>
            <i class="material-icons">perm_identity</i>
          <% end %>
        </li>
        <li class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="로그인">
          <%= link_to new_user_session_path do %>
            <i class="material-icons">lock</i>
          <% end %>
        </li>
      <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
      <% if user_signed_in? %>
        <li>
          <%= link_to posts_path do %>
            <i class="material-icons">find_replace</i><span>여행 찾기</span>
          <% end %>
        </li>
        <li>
          <%= link_to home_recommand_path do %>
            <i class="material-icons">navigation</i><span>여행지 찾기</span>
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user) do %>
            <i class="material-icons">face</i><span>프로필</span>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="material-icons">power_settings_new</i><span>로그아웃</span>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
            <i class="material-icons">perm_identity</i>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <i class="material-icons">lock</i>
          <% end %>
        </li>
      <% end %>
    </ul>
    </div>
  </nav>

app/views/users/index.html.erb
<div class="container">
  <h4>여행자 찾기</h4>
  <div class="divider"></div>
  <br>
  <div class="row">
    <div class="col xl3 l4 m6 s12">
      <div class="card">
        <div class="card-image">
          <%= image_tag('3.png', class:"responsive-img")%>
        </div>
        <div class="card-content">
          <p>탐색꾼</p>
        </div>
      </div>
    </div>
    <div class="col xl3 l4 m6 s12">
      <div class="card">
        <div class="card-image">
          <%= image_tag('profile-demo.jpg', class:"responsive-img")%>
        </div>
        <div class="card-content">
          <p>등대지기</p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col l9 m8 s12">
      <ul class="collection with-header">
        <li class="collection-header">
          <h4><%= @user.name %></h4>
        </li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">email</i>&nbsp;&nbsp;<%= @user.email %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">person</i>&nbsp;&nbsp;<%= @user.name %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">supervisor_account</i>&nbsp;&nbsp;<%= @user.sex %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">home</i>&nbsp;&nbsp;<%= @user.address %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">phone_iphone</i>&nbsp;&nbsp;<%= @user.tele_phone %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">directions_bike</i>&nbsp;&nbsp;<%= @user.habbit %></li>

        <li class="collection-item valign-wrapper"><i class="tiny material-icons">accessibility</i>&nbsp;&nbsp;<%= @user.strong_point %></li>
        <li class="collection-item valign-wrapper"><i class="tiny material-icons">star</i>&nbsp;&nbsp;<%= @user.job %></li>
      </ul>
      <% if @user == current_user %>
        <%= link_to "프로필 수정하기", edit_user_registration_path, class: "waves-effect waves-light btn green lighten-1 wd100" %>
      <% end %>
      <br>
      <br>
    </div>
  </div>
</div>